export interface ICD10Code {
  code: string;
  description: string;
}

export const icd10PsychCodes: ICD10Code[] = [
  { code: 'F20.0', description: 'Paranoid Schizophrenia' },
  { code: 'F20.1', description: 'Disorganized Schizophrenia' },
  { code: 'F20.2', description: 'Catatonic Schizophrenia' },
  { code: 'F20.9', description: 'Schizophrenia, Unspecified' },
  { code: 'F25.0', description: 'Schizoaffective Disorder, Bipolar Type' },
  { code: 'F25.1', description: 'Schizoaffective Disorder, Depressive Type' },
  { code: 'F31.0', description: 'Bipolar I Disorder, Current Episode Hypomanic' },
  { code: 'F31.1', description: 'Bipolar I Disorder, Current Episode Manic Without Psychotic Features' },
  { code: 'F31.2', description: 'Bipolar I Disorder, Current Episode Manic With Psychotic Features' },
  { code: 'F31.4', description: 'Bipolar I Disorder, Current Episode Depressed, Severe, Without Psychotic Features' },
  { code: 'F31.5', description: 'Bipolar I Disorder, Current Episode Depressed, Severe, With Psychotic Features' },
  { code: 'F31.6', description: 'Bipolar I Disorder, Current Episode Mixed' },
  { code: 'F31.9', description: 'Bipolar Disorder, Unspecified' },
  { code: 'F32.0', description: 'Major Depressive Disorder, Single Episode, Mild' },
  { code: 'F32.1', description: 'Major Depressive Disorder, Single Episode, Moderate' },
  { code: 'F32.2', description: 'Major Depressive Disorder, Single Episode, Severe Without Psychotic Features' },
  { code: 'F32.3', description: 'Major Depressive Disorder, Single Episode, Severe With Psychotic Features' },
  { code: 'F32.9', description: 'Major Depressive Disorder, Single Episode, Unspecified' },
  { code: 'F33.0', description: 'Major Depressive Disorder, Recurrent, Mild' },
  { code: 'F33.1', description: 'Major Depressive Disorder, Recurrent, Moderate' },
  { code: 'F33.2', description: 'Major Depressive Disorder, Recurrent, Severe Without Psychotic Features' },
  { code: 'F33.3', description: 'Major Depressive Disorder, Recurrent, Severe With Psychotic Features' },
  { code: 'F33.9', description: 'Major Depressive Disorder, Recurrent, Unspecified' },
  { code: 'F41.0', description: 'Panic Disorder' },
  { code: 'F41.1', description: 'Generalized Anxiety Disorder (GAD)' },
  { code: 'F41.9', description: 'Anxiety Disorder, Unspecified' },
  { code: 'F42.2', description: 'Mixed Obsessional Thoughts and Acts' },
  { code: 'F42.9', description: 'Obsessive-Compulsive Disorder, Unspecified' },
  { code: 'F43.0', description: 'Acute Stress Reaction' },
  { code: 'F43.1', description: 'Post-Traumatic Stress Disorder (PTSD)' },
  { code: 'F43.10', description: 'Post-Traumatic Stress Disorder, Unspecified' },
  { code: 'F43.12', description: 'Post-Traumatic Stress Disorder, Chronic' },
  { code: 'F43.21', description: 'Adjustment Disorder With Depressed Mood' },
  { code: 'F43.22', description: 'Adjustment Disorder With Anxiety' },
  { code: 'F43.23', description: 'Adjustment Disorder With Mixed Anxiety and Depressed Mood' },
  { code: 'F44.0', description: 'Dissociative Amnesia' },
  { code: 'F44.1', description: 'Dissociative Fugue' },
  { code: 'F44.81', description: 'Dissociative Identity Disorder' },
  { code: 'F45.1', description: 'Undifferentiated Somatoform Disorder' },
  { code: 'F50.01', description: 'Anorexia Nervosa, Restricting Type' },
  { code: 'F50.02', description: 'Anorexia Nervosa, Binge Eating/Purging Type' },
  { code: 'F50.2', description: 'Bulimia Nervosa' },
  { code: 'F50.9', description: 'Eating Disorder, Unspecified' },
  { code: 'F60.0', description: 'Paranoid Personality Disorder' },
  { code: 'F60.1', description: 'Schizoid Personality Disorder' },
  { code: 'F60.2', description: 'Antisocial Personality Disorder' },
  { code: 'F60.3', description: 'Borderline Personality Disorder' },
  { code: 'F60.4', description: 'Histrionic Personality Disorder' },
  { code: 'F60.5', description: 'Obsessive-Compulsive Personality Disorder' },
  { code: 'F60.6', description: 'Avoidant Personality Disorder' },
  { code: 'F60.7', description: 'Dependent Personality Disorder' },
  { code: 'F60.9', description: 'Personality Disorder, Unspecified' },
  { code: 'F70', description: 'Mild Intellectual Disability' },
  { code: 'F71', description: 'Moderate Intellectual Disability' },
  { code: 'F90.0', description: 'Attention-Deficit/Hyperactivity Disorder, Predominantly Inattentive Type' },
  { code: 'F90.1', description: 'Attention-Deficit/Hyperactivity Disorder, Predominantly Hyperactive Type' },
  { code: 'F90.2', description: 'Attention-Deficit/Hyperactivity Disorder, Combined Type' },
  { code: 'F90.9', description: 'Attention-Deficit/Hyperactivity Disorder, Unspecified Type' },
  { code: 'F91.1', description: 'Conduct Disorder, Childhood-Onset Type' },
  { code: 'F91.2', description: 'Conduct Disorder, Adolescent-Onset Type' },
  { code: 'F91.9', description: 'Conduct Disorder, Unspecified Onset' },
  { code: 'F98.8', description: 'Other Specified Behavioral and Emotional Disorders with Onset Usually Occurring in Childhood and Adolescence' }
]; 