import { NextRequest, NextResponse } from 'next/server';

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData();
    const file = formData.get('file') as File | null;
    const transcript = formData.get('transcript') as string | null;

    if (!file) {
      return NextResponse.json({ error: 'No audio file provided' }, { status: 400 });
    }

    console.log(`Received file: ${file.name}, size: ${file.size}, type: ${file.type}`);
    
    // Simply return the transcript that was already generated by the Web Speech API
    // If no transcript was sent, return an empty string
    return NextResponse.json({ transcript: transcript?.trim() || '' });

  } catch (error) {
    console.error('Error processing audio file:', error);
    const errorMessage = error instanceof Error ? error.message : 'Unknown error';
    return NextResponse.json(
      { error: `Failed to process audio. ${errorMessage}` },
      { status: 500 }
    );
  }
} 